language: go
go:
  - '1.4'
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - "go get -d -v -t ./..."
  - "go build github.com/digitalocean/doctl/cmd/doctl"
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
deploy:
  provider: releases
  api_key:
    secure: "KUDXlE8mel8UxqupVRZIiaZ5YGWpNvc2jnLZZXAeXR6jHYKs61m1jXX5u809cUJMqmCLsozlMbAji3GwtJao+P/ob1W5bErrwH6xg8eUtv+
dkaK14Ed7famwoSjmHOVmyQnu55g1Gn49K5fqFJfLJwnbWhEomr0ctasagya6UbJBVvrL3Wr51zgeqg5lK6rhzQBbVKNGwpkzMex10ZHdq3TIS5bOc7PxZ
OXYEWONWZL+ufBfbTQPb4Ewk9oM965WR0G9Gbhbaks7sEELj35zxTD1pEOAiIw22Lk5fX0Md74CCa+LPLFUn2nFTOdmERUiL0s5xmsZ+F0cP+hcAiPIfki
PyQelz7cTmp3AKa4sU78UtSio5qUuYPHF3nPVJDhtg1tK/tQplF9iCP0DrQlah8LGMfGGVvyC/JBm98euegXtld0/k5HWS0r2tta+TFLh6jwvd7bBMkDdH
Ml9yZvAz1k4z8Phy8YfUxXDk/NJ0FqLkk9j+6vemJAbBzNVLvwcYRaxogruG4QqEtxiYMtDdMMSEOEXpRB9DLNaItsj+uoam334KsDr30tDye4z6MKMqlT
wBtbwzJ/fk8NzpxDA06P3fSGP2AMLurdky+dVgohnOM/IC3yKMUV+SYvf8PezETk4GaJMND13xRfjh1Yjil3MPxnIIZz5NuxVNUwvzIg="
  file: "doctl"
  skip_cleanup: true
  on:
    repo: digitalocean/doctl
    tags: true
    all_branches: true
